#!/bin/bash

#
# This program is free software; you can use it, redistribute it
# and / or modify it under the terms of the GNU General Public License
# (GPL) as published by the Free Software Foundation; either version 3
# of the License or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program, in a file called gpl.txt or license.txt.
# If not, write to the Free Software Foundation Inc.,
# 59 Temple Place - Suite 330, Boston, MA  02111-1307 USA
#

OPTIND=1

MAGIC_MIME_TYPE="application/x-rep-stats"
HANDLER="repudiator-stats"
HOSTNAME="localhost"
PORT=""
VERBOSE=0
ONLY_IPV4=""

while getopts "h:ha:p:v4" opt; do
  case "$opt" in
  h)
    HOSTNAME=$OPTARG
    ;;
  ha)
    HANDLER=$OPTARG
    ;;
  p)
    PORT=":$OPTARG"
    ;;
  v)
    VERBOSE=1
    ;;
  4)
    ONLY_IPV4="-4"
    ;;
  esac
done

shift $((OPTIND - 1))

if [[ -n "$HOSTNAME" ]]; then
  stats=$(curl --header "Accept: $MAGIC_MIME_TYPE" -s http://$HOSTNAME$PORT/$HANDLER $ONLY_IPV4)

  if [[ -n "$stats" ]]; then
    version=$(echo "$stats" | jq '.version' -r | grep -v "null")
    requests=$(echo "$stats" | jq '.requests')
    blocked=$(echo "$stats" | jq '.blocked')
    warned=$(echo "$stats" | jq '.warned')
    powRequests=$(echo "$stats" | jq '.powRequests')
    powCIFailed=$(echo "$stats" | jq '.powCIFailed')
    powCompleted=$(echo "$stats" | jq '.powCompleted')

    [ $blocked -ne 0 ] && perBlocked=$(awk -v x="$requests" -v y="$blocked" 'BEGIN {printf "%.2f", 100 / x * y}') || perBlocked=0
    [ $warned -ne 0 ] && perWarned=$(awk -v x="$requests" -v y="$warned" 'BEGIN {printf "%.2f", 100 / x * y}') || perWarned=0
    [ $powRequests -ne 0 ] && perPOWRequests=$(awk -v x="$requests" -v y="$powRequests" 'BEGIN {printf "%.2f", 100 / x * y}') || perPOWRequests=0
    [ $powCIFailed -ne 0 ] && perPOWCIFailed=$(awk -v x="$powRequests" -v y="powCIFailed" 'BEGIN {printf "%.2f", 100 / x * y}') || perPOWCIFailed=0
    [ $powCompleted -ne 0 ] && perPOWCompleted=$(awk -v x="$powRequests" -v y="$powCompleted" 'BEGIN {printf "%.2f", 100 / x * y}') || perPOWCompleted=0

    [ $VERBOSE -gt 0 ] && echo $stats

    [ -n "$version" ] && status="OK ($version)" || status="OK"

    echo "$status - PercentBlocked:$perBlocked% PercentWarned:$perWarned% PercentPOWRequests:$perPOWRequests% PercentPOWCIFailed:$perPOWCIFailed% PercentPOWCompleted:$perPOWCompleted% | PercentBlocked=$perBlocked%;; PercentWarned=$perWarned%;; PercentPOWRequests=$perPOWRequests%;; PercentPOWCIFailed=$perPOWCIFailed%;; PercentPOWCompleted=$perPOWCompleted%;;"
  else
    echo "WARNING: No Data"
    exit 1
  fi
else
  echo "$0 -{h [HOSTNAME]} {-ha [HANDLER]} {-p [PORT]} {-v}"
  exit 3
fi
