name: mod_repudiator CI

on: [ push, pull_request ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt -y install gcc apache2-dev libmaxminddb-dev libpcre2-dev

      - name: Build module
        run: apxs -c mod_repudiator.c -lmaxminddb

  build-rocky8:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:8
    steps:
      - uses: actions/checkout@v4

      - name: Install EPEL
        run: dnf -y install epel-release

      - name: Enable crb
        run: crb enable

      - name: Install dependencies
        run: dnf -y install gcc httpd-devel libmaxminddb-devel pcre2-devel redhat-rpm-config

      - name: Build module
        run: apxs -c mod_repudiator.c -lmaxminddb

  build-rocky9:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9
    steps:
      - uses: actions/checkout@v4

      - name: Install EPEL
        run: dnf -y install epel-release

      - name: Enable crb
        run: crb enable

      - name: Install dependencies
        run: dnf -y install gcc httpd-devel libmaxminddb-devel pcre2-devel redhat-rpm-config

      - name: Build module
        run: apxs -c mod_repudiator.c -lmaxminddb
